name: Deploy keycloak-bend

# Set custom run name to show project name in workflow runs list
run-name: "Deploy keycloak-bend ${{ inputs.environment }} ${{ inputs.image_tag }}"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Select the environment
        required: true
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  IMAGE_NAME: "arxiv-keycloak"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Format check
        run: terraform fmt -check

  deploy:
    runs-on: ubuntu-latest
    needs: format-check
    environment: ${{ inputs.environment }}
    if: >
      (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch') &&
      ((inputs.env != 'production' && inputs.env != 'prod' && inputs.env != 'staging' && inputs.env != 'stage') || inputs.image_tag != 'latest')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          TERRAFORM_ARGS="-var=\"keycloak_image=gcr.io/arxiv-development/${{env.IMAGE_NAME}}:${{inputs.image_tag}}\""

          echo "TERRAFORM_ARGS=$TERRAFORM_ARGS" >> $GITHUB_ENV
  
      - name: Authenticate with target project workload identity
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github/providers/github-actions-provider
          service_account: github-actions-sa@${{ vars.PROJECT_NAME }}.iam.gserviceaccount.com
          project_id: ${{ vars.PROJECT_NAME }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Initialize keycloak-db remote backend (for db output variables)
        run: |
          terraform init -backend-config="bucket=${{ env.TERRAFORM_BUCKET }}"
          TERRAFORM_ARGS="$TERRAFORM_ARGS \
              -var=\"auth_db_private_ip=$(terraform output -raw private_ip_address)\" \
              -var=\"use_cloud_sql_proxy=false\" \
              -var=\"auth_db_name=$(terraform output -raw database_name)\" \
              -var=\"db_user=$(terraform output -raw keycloak_user_name)\" \
              -var=\"keycloak_db_password_secret_name=$(terraform output -raw keycloak_password_secret_name)\""
          echo "TERRAFORM_ARGS=$TERRAFORM_ARGS" >> $GITHUB_ENV
        working-directory: terraform/keycloak-db

      - name: Initialize keycloak-svc remote backend
        run: terraform init -backend-config="bucket=${{ env.TERRAFORM_BUCKET }}"
        working-directory: terraform/keycloak-service

      - name: Apply
        run: |
          echo "TERRAFORM_ARGS=$TERRAFORM_ARGS"
          #terraform apply -var-file=envs/${{ vars.ENV_VAR }}.tfvars ${{ env.TERRAFORM_ARGS }} -auto-approve
        working-directory: terraform/keycloak-service