name: Test bizlogic

on:
  pull_request:
    paths:
      - 'bizlogic/**'
      - '.github/workflows/test-bizlogic.yaml'
  push:
    branches:
      - master
      - main
    paths:
      - 'bizlogic/**'
      - '.github/workflows/test-bizlogic.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y mysql-client

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry --version

      - name: Cache poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-bizlogic-${{ hashFiles('bizlogic/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-bizlogic-

      - name: Install dependencies
        working-directory: bizlogic
        run: poetry install

      - name: Run database tests with MySQL docker
        working-directory: bizlogic
        run: poetry run pytest auth/legacy/tests --db=mysql -v

      - name: Run other tests with coverage
        working-directory: bizlogic
        run: poetry run pytest --cov=arxiv --cov-fail-under=40 arxiv --ignore=arxiv/base --ignore=arxiv/auth/legacy -v
